apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mongo
    #app: todoapp
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017
  