apiVersion: v1
kind: Service
metadata:
  name: j-hello
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
