apiVersion: "v1"
kind: Pod
metadata:
  name: nginx
  labels:
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: my-vol
  volumes:
    - name: my-vol
      hostPath: 
        path: /var/lib/my-data 